/**
 * Accept canonical endpoint names plus one optional trailing slash. Encoded
 * aliases must never be decoded by the native router after bypassing our gates.
 * Password-reset tokens use the URI-unreserved alphabet generated by BA.
 */
export function canonicalAuthPath(pathname: string): string | null {
  if (!pathname.startsWith("/api/auth/") || pathname.includes("//")) return null;
  const path = pathname.slice("/api/auth".length).replace(/\/$/, "");
  if (/^\/reset-password\/[A-Za-z0-9._~-]{1,512}$/.test(path)) return path;
  return /^\/[a-z-]+(?:\/[a-z-]+)*$/.test(path) ? path : null;
}
